<?php 

if(isset($_POST['eng'])){
	$_SESSION["lang"] = "eng";
} elseif(isset($_POST['ger'])){
	$_SESSION["lang"] = "ger";
} elseif(isset($_POST['slo'])){
	$_SESSION["lang"] = "slo";
}

if(strlen($_SESSION["lang"]) < 1){
	$x = "eng";
} else {
	$x = $_SESSION["lang"];
}

// if(isset($_POST['eng'])){
// 	$_SESSION["lang"] = "eng";
// 	$db2 = "";
// } elseif(isset($_POST['ger'])){
// 	$_SESSION["lang"] = "ger";
// 	$db2 = "_de";
// } elseif(isset($_POST['slo'])){
// 	$_SESSION["lang"] = "slo";
// 	$db2 = "_sk";
// }
//  var_dump($_SESSION["lang"]);

// if(strlen($_SESSION["lang"]) < 1){
// 	$x = "eng";
// 	$db2 = '_sk';
// } else {
// 	$x = $_SESSION["lang"];
// }



$languages = array(
	"eng"=>array(
		// messages
		"success"=> "Success!",
		"up_success"=> "Uploaded successfully!",
		// small menu, top right corner
		"notification1"=> "New Adpotion request!",
		"notification2"=> "New Support request!",
		"notification3"=> "New Buying request!",
		// side menu
		"dashboard"=> "Dashboard",
		"dashboard1" => "Start Admin Page",
		"dashboard2"=> "Go Main Page",
		"dogs"=> "Dogs",
		"dogs1"=> "Upload Dog",
		"dogs2"=> "Edit Dog",
		"dogs3"=> "Edit Dog Image",
		"dogs4"=> "Edit Adopted Dog",
		"dogs5"=> "Edit Adopted Dog Image",
		"cats"=> "Cats",
		"cats1"=> "Upload Cat",
		"cats2"=> "Edit Cat",
		"cats3"=> "Edit Cat Image",
		"cats4"=> "Edit Adopted Cat",
		"cats5"=> "Edit Adopted Cat Image",
		"edit"=> "Edit Page",
		"edit1"=> "Edit Support",
		"edit2"=> "Edit Adopt",
		"edit3"=> "Edit Mission",
		"edit4"=> "Edit Help Us",
		"edit5"=> "Edit Running Text",
		"info"=> "Important Info",
		"info1"=> "Upload Info",
		"info2"=> "Edit Info",
		"team"=> "Team",
		"team1"=> "Upload Team",
		"team2"=> "Edit Team",
		"sponsor"=> "Sponsors",
		"sponsor1"=> "Upload Sponsors",
		"sponsor2"=> "Edit Sponsors",
		"reports"=> "Reports",
		"reports1"=> "Upload Report",
		"reports2"=> "Edit Reports",
		"reports3"=> "Upload Annual Report",
		"reports4"=> "Edit Annual Reports",
		"shelter" => "Shelter",
		"shelter1" => "Upload Shelter",
		"shelter2" => "Edit Shelter",
		"user" => "Admin Users",
		"user1"=> "Upload Users",
		"user2"=> "Edit Users",
		"support"=> "Supporters",
		"support1"=> "List Supporters",
		"support2"=> "Waiting Supporter",
		"adopt"=> "Adopters",
		"adopt1"=> "List Adopters",
		"adopt2"=> "Waiting Adopters",
		"selling"=> "Selling",
		"selling1"=> "List E-Shop",
		"selling2"=> "Upload E-Shop",
		"selling3"=> "List Auction",
		"selling4"=> "Upload Auction",
		"logout" => "Log Out",
		// landingpage requests
		"news"=> "News",
		"request1"=> "Adoption request from: ",
		"request2"=> "Support request from: ",
		"request3" => "Buying request from: ",
		"request4"=> "Waiting for verification",
		"request5"=> "Waiting for handle",
		// upload dog & cat
		"up_title"=> "Dog upload", // DOG
		"up_title1" => "Cat upload",
		"up_name"=> "Name",
		"up_id" => "ID",
		"up_gender" => "Gender",
		"up_born" => "Born data",
		"up_cast" => "Castration",
		"up_height"=> "Height",
		"up_weight" => "Weight",
		"up_breed" => "Breed",
		"up_desc" => "Description",
		"up_next_btn" => "Next",
		"up_post_date"=> "Post Date",
		"up_type"=> "Type",
		"up_live"=> "1 = in shelter | 2 = R.I.P.",
		"up_living"=>"In shelter",
		// image upload
		"up_img1"=> "Upload profile picture",
		"up_skip_btn"=> "SKIP IMAGE UPLOAD",
		"up_del_btn" => "Delete",
		"up_edit_btn" => "Edit",
		"up_update_btn"=> "Update",
		"up_undo_btn"=> "Undo Adoption",
		"up_img4"=> "Upload other pictures",
		"up_load_btn"=> "UPLOAD",
		// Edit dog
		"edit_dog_title"=> "Edit Dog images",
		"select_dog"=> "Select Dog",
		// Edit cat
		"edit_cat_title"=> "Edit Cat images",
		"select_cat"=> "Select Cat",
		// Select
		"select"=> "Select",
		// Edit images
		"img_title"=> "Edit Images",
		"img_del_title"=> "Delete Pictures",
		// edit pages
		"edit_title" => "Title",
		"upload_info"=> "Upload Info",
		// team page
		"team_title"=> "Team Upload",
		"team_name"=> "Team Member Name",
		"team_pos"=> "Position",
		"team_desc"=> "Description",
		"team_edit"=> "Edit team",
		// Sponsors page
		"spon_title"=> "Sponsors Upload",
		"spon_name"=> "Sponsor Name",
		"address"=> "Address",
		// Report Upl
		"rep_title"=> "Report Upload",
		"rep_name"=> "Report Title",
		"rep_date"=> "Date",
		"rep_keywords"=> "Keywords (for search)",
		"rep_action"=> "Actions",
		// annual report
		"anrep_title"=> "Upload PDF file",
		"anrep_name"=> "Name of file",
		"anrep_year"=> "Year",
		"anrep_edit"=> "Delete Annual Report PDF file",
		// shelter
		"shelter_img"=> "Upload Image",
		// admin
		"admin_title"=> "Add new User",
		"admin_name"=> "Username",
		"admin_pass" => "Password",
		"admin_pass2"=> "Repeat password",
		// supporters
		"city"=> "City",
		"street"=> "Street",
		"zip"=> "Zip",
		"req_date"=> "Req. date",
		"suppet" => "Supported Pet",
		"petev"=> "Pet ID",
		"supdog"=> "Supported Dog",
		"supcat"=> "Supported Cat",
		"verify"=> "Verification",
		"allow"=> "Allow",
		// adopters
		"kind"=> "Kind",
		"other_pets"=> "Other pets",
		"kind_pets" => "Kind of pets",
		"pet_id" => "Supported pet",
		// store
		"products"=> "Products",
		"product"=> "Product",
		"w_c"=> "Waiting Customers",
		"price"=> "Price",
		"condition"=> "Condition",
		"quantity"=> "Quantitiy",
		"comment"=> "Comment",
		"pr_id"=> "Product ID",
		"contacted"=> "Contacted",
		"del/sold"=> "Delete/sold",
		"del/finish"=> "Delete/Finish",
		"hand_cust"=> "Handled Customers",
		"up_pr"=> "Product Upload",
		"name_pr"=> "Product Name",
		"new"=> "New",
		"used"=> "Used",
		"type_pr"=> "Type of Product",
		"other"=> "Other",
		"col_lea"=> "Collar, leash",
		"cloth"=> "Cloth",
		"first_price"=> "First Price",
		"post_date"=> "Post Date",
		"end_auct"=> "End Date",
		"see_bid"=> "See bids",
		"from"=> "From",
		"up_auc"=> "Upload auction",
		"up_auc2"=> "Auction Product Upload",
		"bid_id"=> "Bid ID",
		"bid"=> "Bid",
		"bid_date"=> "Bid date",
		"you_have" => "You have",
		"notif" => "notifications",
		"provide_value" => "Provide value",
		"evidence_id" => "Evidence ID",
		"modal_title" => "Confirm",
		"modal_question" => "Do you really want to delete this recod/dog/cat?",
		"check_out" => "Check out",
		"cat_id" => "cat id",
		"dog_id" => "dog id",
		"adopters_full_name" => "adopters_full_name",
		"yes" => "yes",
		"no" => "no",
		"kind_of_keeping" => "Kind of keeping",
		"inside" => "Inside",
		"outside" => "Outside",
		"in_out" => "Inside & Outside",
		"other_pets" => "Other pets in the household",
		"other_pets2" => "Other pets in the household",
		"address" => "Address",
		"optional" => "Optional",
		"adopt_btn" => "Adopt",
		"adopt_msg" => "Thank you, your adoption request has been sent successfully! We will contact you soon.",
		"add_dog_adopter" => "Add dog adopter",
		"add_cat_adopter" => "Add cat adopter"
		),
	"ger"=>array(
		// messages
		"success"=> "Success!",
		"up_success"=> "Uploaded successfully!",
		// small menu, top right corner
		"notification1"=> "New Adpotion request!",
		"notification2"=> "New Support request!",
		"notification3"=> "New Buying request!",
		// side menu
		"dashboard"=> "Dashboard",
		"dashboard1" => "Start Admin Page",
		"dashboard2"=> "Go Main Page",
		"dogs"=> "Dogs",
		"dogs1"=> "Upload Dog",
		"dogs2"=> "Edit Dog",
		"dogs3"=> "Edit Dog Image",
		"dogs4"=> "Edit Adopted Dog",
		"dogs5"=> "Edit Adopted Dog Image",
		"cats"=> "Cats",
		"cats1"=> "Upload Cat",
		"cats2"=> "Edit Cat",
		"cats3"=> "Edit Cat Image",
		"cats4"=> "Edit Adopted Cat",
		"cats5"=> "Edit Adopted Cat Image",
		"edit"=> "Edit Page",
		"edit1"=> "Edit Support",
		"edit2"=> "Edit Adopt",
		"edit3"=> "Edit Mission",
		"edit4"=> "Edit Help Us",
		"edit5"=> "Edit Running Text",
		"info"=> "Important Info",
		"info1"=> "Upload Info",
		"info2"=> "Edit Info",
		"team"=> "Team",
		"team1"=> "Upload Team",
		"team2"=> "Edit Team",
		"sponsor"=> "Sponsors",
		"sponsor1"=> "Upload Sponsors",
		"sponsor2"=> "Edit Sponsors",
		"reports"=> "Reports",
		"reports1"=> "Upload Report",
		"reports2"=> "Edit Reports",
		"reports3"=> "Upload Annual Report",
		"reports4"=> "Edit Annual Reports",
		"shelter" => "Shelter",
		"shelter1" => "Upload Shelter",
		"shelter2" => "Edit Shelter",
		"user" => "Admin Users",
		"user1"=> "Upload Users",
		"user2"=> "Edit Users",
		"support"=> "Supporters",
		"support1"=> "List Supporters",
		"support2"=> "Waiting Supporter",
		"adopt"=> "Adopters",
		"adopt1"=> "List Adopters",
		"adopt2"=> "Waiting Adopters",
		"selling"=> "Selling",
		"selling1"=> "List E-Shop",
		"selling2"=> "Upload E-Shop",
		"selling3"=> "List Auction",
		"selling4"=> "Upload Auction",
		"logout" => "Log Out",
		// landingpage requests
		"news"=> "News",
		"request1"=> "Adoption request from: ",
		"request2"=> "Support request from: ",
		"request3" => "Buying request from: ",
		"request4"=> "Waiting for verification",
		"request5"=> "Waiting for handle",
		// upload dog & cat
		"up_title"=> "Dog upload", // DOG
		"up_title1" => "Cat upload",
		"up_name"=> "Name",
		"up_id" => "ID",
		"up_gender" => "Gender",
		"up_born" => "Born data",
		"up_cast" => "Castration",
		"up_height"=> "Height",
		"up_weight" => "Weight",
		"up_breed" => "Breed",
		"up_desc" => "Description",
		"up_next_btn" => "Next",
		"up_post_date"=> "Post Date",
		"up_type"=> "Type",
		"up_live"=> "1 = in shelter | 2 = R.I.P.",
		"up_living"=>"In shelter",
		// image upload
		"up_img1"=> "Upload profile picture",
		"up_skip_btn"=> "SKIP IMAGE UPLOAD",
		"up_del_btn" => "Delete",
		"up_edit_btn" => "Edit",
		"up_update_btn"=> "Update",
		"up_undo_btn"=> "Undo Adoption",
		"up_img4"=> "Upload other pictures",
		"up_load_btn"=> "UPLOAD",
		// Edit dog
		"edit_dog_title"=> "Edit Dog images",
		"select_dog"=> "Select Dog",
		// Edit cat
		"edit_cat_title"=> "Edit Cat images",
		"select_cat"=> "Select Cat",
		// Select
		"select"=> "Select",
		// Edit images
		"img_title"=> "Edit Images",
		"img_del_title"=> "Delete Pictures",
		// edit pages
		"edit_title" => "Title",
		"upload_info"=> "Upload Info",
		// team page
		"team_title"=> "Team Upload",
		"team_name"=> "Team Member Name",
		"team_pos"=> "Position",
		"team_desc"=> "Description",
		"team_edit"=> "Edit team",
		// Sponsors page
		"spon_title"=> "Sponsors Upload",
		"spon_name"=> "Sponsor Name",
		"address"=> "Address",
		// Report Upl
		"rep_title"=> "Report Upload",
		"rep_name"=> "Report Title",
		"rep_date"=> "Date",
		"rep_keywords"=> "Keywords (for search)",
		"rep_action"=> "Actions",
		// annual report
		"anrep_title"=> "Upload PDF file",
		"anrep_name"=> "Name of file",
		"anrep_year"=> "Year",
		"anrep_edit"=> "Delete Annual Report PDF file",
		// shelter
		"shelter_img"=> "Upload Image",
		// admin
		"admin_title"=> "Add new User",
		"admin_name"=> "Username",
		"admin_pass" => "Password",
		"admin_pass2"=> "Repeat password",
		// supporters
		"city"=> "City",
		"street"=> "Street",
		"zip"=> "Zip",
		"req_date"=> "Req. date",
		"suppet" => "Supported Pet",
		"petev"=> "Pet ID",
		"supdog"=> "Supported Dog",
		"supcat"=> "Supported Cat",
		"verify"=> "Verification",
		"allow"=> "Allow",
		// adopters
		"kind"=> "Kind",
		"other_pets"=> "Other pets",
		"kind_pets" => "Kind of pets",
		"pet_id" => "Supported pet",
		// store
		"products"=> "Products",
		"product"=> "Product",
		"w_c"=> "Waiting Customers",
		"price"=> "Price",
		"condition"=> "Condition",
		"quantity"=> "Quantitiy",
		"comment"=> "Comment",
		"pr_id"=> "Product ID",
		"contacted"=> "Contacted",
		"del/sold"=> "Delete/sold",
		"del/finish"=> "Delete/Finish",
		"hand_cust"=> "Handled Customers",
		"up_pr"=> "Product Upload",
		"name_pr"=> "Product Name",
		"new"=> "New",
		"used"=> "Used",
		"type_pr"=> "Type of Product",
		"other"=> "Other",
		"col_lea"=> "Collar, leash",
		"cloth"=> "Cloth",
		"first_price"=> "First Price",
		"post_date"=> "Post Date",
		"end_auct"=> "End Date",
		"see_bid"=> "See bids",
		"from"=> "From",
		"up_auc"=> "Upload auction",
		"up_auc2"=> "Auction Product Upload",
		"bid_id"=> "Bid ID",
		"bid"=> "Bid",
		"bid_date"=> "Bid date",
		"you_have" => "You have",
		"notif" => "notifications",
		"provide_value" => "Provide value",
		"evidence_id" => "Evidence ID",
		"modal_title" => "Confirm",
		"modal_question" => "Do you really want to delete this recod/dog/cat?",
		"check_out" => "Check out",
		"cat_id" => "cat id",
		"dog_id" => "dog id",
		"adopters_full_name" => "adopters_full_name",
		"yes" => "yes",
		"no" => "no",
		"kind_of_keeping" => "Kind of keeping",
		"inside" => "Inside",
		"outside" => "Outside",
		"in_out" => "Inside & Outside",
		"other_pets" => "Other pets in the household",
		"other_pets2" => "Other pets in the household",
		"address" => "Address",
		"optional" => "Optional",
		"adopt_btn" => "Adopt",
		"adopt_msg" => "Thank you, your adoption request has been sent successfully! We will contact you soon.",
		"add_dog_adopter" => "Add dog adopter",
		"add_cat_adopter" => "Add cat adopter"
	),
	"slo"=>array(
		// messages
		"success"=> "Vykonané!",
		"up_success"=> "Vložené!",
		// small menu top right corner
		"notification1"=> "Nova žiadosť o adopciu!",
		"notification2"=> "Nova žiadosť o podporu!",
		"notification3"=> "Nový dopyt na kúpu!",
		// side menu
		"dashboard"=> "Hlavné panely",
		"dashboard1" => "Admin stránka",
		"dashboard2"=> "Webstránka",
		"dogs"=> "Psíkovia",
		"dogs1"=> "Pridaj psíka",
		"dogs2"=> "Uprav psíka",
		"dogs3"=> "Uprav foto",
		"dogs4"=> "Uprav adopt. psíka",
		"dogs5"=> "Uprav adopt. foto",
		"cats"=> "Mačičky",
		"cats1"=> "Pridaj mačku",
		"cats2"=> "Uprav mačku",
		"cats3"=> "Uprav foto",
		"cats4"=> "Uprav adopt. mačku",
		"cats5"=> "Uprav adopt. foto",
		"edit"=> "Uprav stránku",
		"edit1"=> "Upravo o Patronáte",
		"edit2"=> "Uprav o adopcii",
		"edit3"=> "Uprav Naša misia",
		"edit4"=> "Uprav Ako pomôcť",
		"edit5"=> "Uprav Running Text",
		"info"=> "Dôležité info",
		"info1"=> "Pridaj info",
		"info2"=> "Uprav info",
		"team"=> "Team",
		"team1"=> "Pridaj člena",
		"team2"=> "Uprav člena",
		"sponsor"=> "Sponzori",
		"sponsor1"=> "Pridaj sponzora",
		"sponsor2"=> "Uprav sponzora",
		"reports"=> "Správy",
		"reports1"=> "Pridaj správu",
		"reports2"=> "Uprav správy",
		"reports3"=> "Pridaj výroč. správu",
		"reports4"=> "Uprav výroč. správu",
		"shelter" => "Náš útulok",
		"shelter1" => "Pridaj foto",
		"shelter2" => "Uprav foto",
		"user" => "Admin užívatelia",
		"user1"=> "Pridaj admina",
		"user2"=> "Uprav admina",
		"support"=> "Podporovatelia",
		"support1"=> "Existujúci",
		"support2"=> "Na schválenie",
		"adopt"=> "Osvojitelia",
		"adopt1"=> "Existujúci",
		"adopt2"=> "Na schválenie",
		"selling"=> "Predaj",
		"selling1"=> "Uprav e-shop",
		"selling2"=> "Pridaj produkt",
		"selling3"=> "Existujúca dražba",
		"selling4"=> "Pridaj na draženie",
		"logout" => "Odhlásiť sa",
		// landingpage requests
		"news"=> "Správy",
		"request1"=> "Žiadosť o adopciu od: ",
		"request2"=> "Žiadosť o podporu od: ",
		"request3" => "Dopyt na kúpu od: ",
		"request4"=> "Na overenie",
		"request5"=> "Na riešenie",
		// upload dog & cat
		"up_title"=> "Pridaj psa", // DOG
		"up_title1" => "Pridaj mačku",
		"up_name"=> "Meno",
		"up_id" => "ID",
		"up_gender" => "Pohlavie",
		"up_born" => "Dátum narodenia",
		"up_cast" => "Kastrácia",
		"up_height"=> "Výška",
		"up_weight" => "Váha",
		"up_breed" => "Rasa",
		"up_desc" => "Viac info",
		"up_next_btn" => "Ďalej",
		"up_post_date"=> "Dátum zverejnenia",
		"up_type"=> "Rasa",
		"up_live"=> "1 = v útulku | 2 = R.I.P.",
		"up_living"=>"v útulku",
		// image upload
		"up_img1"=> "Pridaj profilovú foto",
		"up_skip_btn"=> "Preskoč vkladanie foto",
		"up_del_btn" => "Vymaž",
		"up_edit_btn" => "Uprav",
		"up_update_btn"=> "Aktualizuj",
		"up_undo_btn"=> "vziať späť adopciu",
		"up_img4"=> "Pridaj ďalšie foto",
		"up_load_btn"=> "Vlož",
		// Edit dog
		"edit_dog_title"=> "Uprav foto psa",
		"select_dog"=> "Vyber psa",
		// Edit cat
		"edit_cat_title"=> "Uprav foto mačku",
		"select_cat"=> "Vyber mačku",
		// Select
		"select"=> "Zvoľ",
		// Edit images
		"img_title"=> "Uprav foto",
		"img_del_title"=> "Vymaž foto",
		// edit pages
		"edit_title" => "Titulok",
		"upload_info"=> "Uprav info",
		// team page
		"team_title"=> "Pridaj člena",
		"team_name"=> "Meno člena",
		"team_pos"=> "Pozícia",
		"team_desc"=> "Popis",
		"team_edit"=> "Uprav člena",
		// Sponsors page
		"spon_title"=> "Pridaj sponzora",
		"spon_name"=> "Meno sponzora",
		"address"=> "Adresa",
		// Report Upload
		"rep_title"=> "Pridaj správu",
		"rep_name"=> "Titulok",
		"rep_date"=> "Dátum",
		"rep_keywords"=> "Kľúčové slová",
		"rep_action"=> "Akcia",
		// annual report
		"anrep_title"=> "Vlož PDF súbor",
		"anrep_name"=> "Názov súboru",
		"anrep_year"=> "Rok",
		"anrep_edit"=> "Vymaž PDF súbor",
		// shelter
		"shelter_img"=> "Pridaj foto",
		// admin
		"admin_title"=> "Pridaj nového užívateľa",
		"admin_name"=> "Užívateľské meno",
		"admin_pass" => "Heslo",
		"admin_pass2"=> "Zopakuj heslo",
		// supporters
		"city"=> "Mesto",
		"street"=> "Ulica",
		"zip"=> "PSČ",
		"req_date"=> "Dátum žiadosti",
		"suppet" => "Podporené zviera",
		"petev"=> "ID",
		"supdog"=> "Podporený pes",
		"supcat"=> "Podporená mačka",
		"verify"=> "Verifikácia",
		"allow"=> "Dovoliť",
		// adopters
		"kind"=> "Prostredie",
		"other_pets"=> "Iné zvieratá",
		"kind_pets" => "Typ zvieratá",
		"pet_id" => "Záujem o",
		// store
		"products"=> "Produkty",
		"product"=> "Produkt",
		"w_c"=> "Čakajúci zákazníci",
		"price"=> "Cena",
		"condition"=> "Stav",
		"quantity"=> "Množstvo",
		"comment"=> "Pozn.",
		"pr_id"=> "ID položky",
		"contacted"=> "Kontaktovaný",
		"del/sold"=> "Vymaž/Predané",
		"del/finish"=> "Vymaž/Ukonči",
		"hand_cust"=> "Riešení zákazníci",
		"up_pr"=> "Pridaj Produkt",
		"name_pr"=> "Názov produktu",
		"new"=> "Nový",
		"used"=> "Použitý",
		"type_pr"=> "Typ produktu",
		"other"=> "Iný",
		"col_lea"=> "Obojok, vodítko",
		"cloth"=> "Oblečky",
		"first_price"=> "Vyvolávacia cena",
		"post_date"=> "Zverejnené",
		"end_auct"=> "Koniec aukcie",
		"see_bid"=> "Ponuky",
		"from"=> "Od",
		"up_auc"=> "Pridaj dražbu",
		"up_auc2"=> "Pridaj produkt do aukcie",
		"bid_id"=> "ID ponuky",
		"bid"=> "Ponuka",
		"bid_date"=> "Dátum ponuky",
		"you_have" => "Máš",
		"notif" => "oznámení",
		"provide_value" => "Pridaj hodnotu",
		"evidence_id" => "Evidenč. ID",
		"modal_title" => "Zmazať",
		"modal_question" => "Naozaj chceš vymazať tento záznam/psíka/mačku?",
		"check_out" => "Skontrolovať",
		"cat_id" => "cat id",
		"dog_id" => "dog id",
		"adopters_full_name" => "adopters_full_name",
		"yes" => "yes",
		"no" => "no",
		"kind_of_keeping" => "Podmienky",
		"inside" => "Vnútri",
		"outside" => "Vonku",
		"in_out" => "Vnútri & Vonku",
		"other_pets" => "Iné zvieratá v domácnosti",
		"other_pets2" => "Druh zvierat v domácnosti",
		"address" => "Adresa",
		"optional" => "nepovinné",
		"adopt_btn" => "Chcem adoptovať",
		"adopt_msg" => "Ďakujeme, vaša žiadosť o Adopciu bola úspešne odoslaná! Budeme vás čoskoro kontaktovať.",
		"add_dog_adopter" => "Add dog adopter",
		"add_cat_adopter" => "Add cat adopter"
		
	)
	);
include_once("includes_admin/dbh.inc.php");
 ?>