<?php

if(isset($_COOKIE['lang2'])){
	$x = $_COOKIE['lang2'];
} else {
	$x = 'sk';
}

if(isset($_POST['en'])){
	$_SESSION["lang2"] = "eng";
	setcookie('lang2', 'en', 0, '/');
	$x = 'en';
} elseif(isset($_POST['de'])){
	$_SESSION["lang2"] = "ger";
	setcookie('lang2', 'de', 0, '/');
	$x = 'de';
} elseif(isset($_POST['sk'])){
	$_SESSION["lang2"] = "slo";
	setcookie('lang2', 'sk', 0, '/');
	$x = 'sk';
}


$languages = array(
	"en"=>array(
		"page_title" => "Piešťany Animal Shelter",
		"ABOUT_US" => "ABOUT US",
		"DOGS&CATS" => "DOGS & CATS",
		"REPORTS" => "REPORTS",
		"OTHER" => "OTHER",
		"CONTACT" => "CONTACT",
		"WELCOME_AT" => "WELCOME AT",
		"donate" => "donate",
		"OUR_MISSION"=> "OUR MISSION",
		"OUR_TEAM" => "OUR TEAM",
		"IMPORTANT_INFO"=> "IMPORTANT INFO",
		"SPONSORS" => "SPONSORS",
		"GALLERY" => "PHOTOS",
		"DOGS" => "DOGS",
		"CATS" => "CATS",
		"SEARCH" => "SEARCH",
		"ADOPT" => "ADOPT",
		"SUPPORT" => "PATRONAGE",
		"HELP" => "HOW TO SUPPORT?",
		"IN_HAPPY_HOME" => "IN HAPPY HOME",
		"IN_MEMORIAM" => "IN MEMORIAM",
		"E-SHOP" => "E-SHOP",
		"AUCTION" => "AUCTION",
		"REPAIRS" => "REPAIRS PLAN",
		"SOS_CARD" => "SOS card",
		"SOS_CARDdoc" => "SOS_card",
		"looking_for" => "Look for a new home...",
		"male" => "Male",
		"female" => "Female",
		"cat_male" => "Male",
		"cat_female" => "Female",
		"our_mission" => "Our mission",
		"how_adopt" => "How to adopt?",
		"why_support" => "Why support?",
		"about_adopt" => "About adopting",
		"about_support" => "More about support",
		"visitors" => "Visitors",
		"saved_dogs" => "Saved dogs",
		"saved_cats" => "Saved cats",
		"meet_team" => "Meet our team",
		"our_sponsors" => "Our Sponsors",
		"our_place" => "Our Animal Shelter",
		"search_title" => "Search for a specified pet?",
		"select_type" => "Select the type of pet",
		"select_gender" => "Select gender",
		"castration" => "Castration",
		"select_age" => "Select age",
		"search" => "Search",
		"adopt_title" => "Why and how to adopt?",
		"adopt_subtitle1"=> "Adopting a puppy can be exciting. You are choosing a new companion for many years to come...",
		"our_advice"=>"Our advice...",
		"support_title" => "Become a proud Patron!",
        "support_subtitle" => "Little big help for animals in our shelter.",
		"help_title" => "Why and how to support?",
		"help_subtitle" => "Our ability to help stray animals depends solely on support from people like you – people with good heart…",
		"dog" => "Dog",
		"cat" => "Cat",
		"male" => "Male",
		"female" => "Female",
		"yes" => "Yes",
		"no" => "No",
		"adopted_title" => "Adopted",
		"inmemoriam_title" => "In Memoriam...",
		"inmemoriam_subtitle" => "This is just some placeholder text, need to update!!!",
		"reports_title" => "Reports",
		"annual_reports" => "Annual reports (SK)",
		"reports_archive" => "Reports archive",
		"read_more" => "Read more...",
		"page" => "Page",
		"out_of" => "out of",
		"products" => "Products",
		"product" => "Product",
		"eshop_subtitle" => "Just some random text, need to update",
		"eshop_col1"=> "Clothes",
		"eshop_col2" => "Collar, leash",
		"eshop_col3"=> "Other",
		"over" => "over",
		"auction" => "Auction",
		"auction_subtitle" => "Random text, need to update",
		"bid_price" => "Acutal bid price",
		"first_price" => "First price",
		"end_date" => "End date",
		"make_bid" => "Make a bid",
		"contact_title"=> "Have a question? Contact us",
		"contact" => "Contact",
		"contact_sub" => "Please contact us in person, by phone or via email. Thank you.",
		"an_home" => "Shelter address",
		"an_home_sub" => "Priemyselná 12a, Piešťany, Slovakia <br> GPS coordinates: +48° 35' 57.18\", +17° 48' 44.32\"",
		"more" => "More...",
		"support" => "Support",
		"adopt_menu" => "Adopt",
		"name"=> "Name",
		"gender" => "Gender",
		"breed" => "Breed",
		"born" => "Born",
		"height" => "Height",
		"weight" => "Weight",
		"description" => "Description",
		"provide_value" => "Provide value",
		"dogs" => "Dogs",
		"cats"=> "Cats",
		"visit_us" => "Visit Us",
		"quick_links" => "Quick links",
		"footer_find" => "Where to find us?",
		"footer_open" => "Priemyselná 12a, Piešťany, Slovakia<br><br>November – February: 8 - 16 h <br>- Dog Walks 13 - 15.30 h<br>
March – October:<br>
Workdays: 8 - 16 h<br> - Dog Walks 13 - 15.30 h<br>
Saturday, Sunday: 8 - 17 h <br>- Dog Walks 13 - 16.30 h<br><br>We are open 365 days a year!",
		"footer_row1" => "Priemyselná 12a, Piešťany, Slovakia",
		"footer_row2" => "Tel: +421 904 170 913, We speak <br> English!",
		"footer_row4" => "utulok@utulok-piestany.sk",
		"footer_row3" => "IBAN: SK5011000000002926886043<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;BIC: TATRSKBXXXX",
		"close" => "Close",
		"support_modal_title" => "Support",
		"your_full_name" => "Your full name",
		"ZIP" => "ZIP",
		"city" => "City",
		"street" => "Street",
		"support_btn" => "Support",
		"support_msg" => "Thank you, your support request has been sent successfully! We will contact you soon.",
		"adopt_modal_title"=> "Adopt",
		"kind_of_keeping" => "Kind of keeping",
		"inside" => "Inside",
		"outside" => "Outside",
		"in_out" => "Inside & Outside",
		"other_pets" => "Other pets in the household",
		"other_pets2" => "Other pets in the household",
		"address" => "Address",
		"optional" => "Optional",
		"adopt_btn" => "Adopt",
		"adopt_msg" => "Thank you, your adoption request has been sent successfully! We will contact you soon.",
		"nick_name" => "Nick name (shown on the page)",
		"not_public" => "not public",
		"your_bid" => "Your bid",
		"comment" => "Comment",
		"not_required" => "not required",
		"bid_btn" => "Make bid",
		"bid_msg" => "Sent successfully!",
		"buy" => "Buy",
		"buy_btn"=> "Buy",
		"description" => "Description",
		"price"=> "Price",
		"quantity" => "Quantity",
		"condition" => "Condition",
		"type" => "Type",
		"contact_open" => "<p>November – February: 8 - 16 h / Dog Walks 13 - 15.30 h
</p><p>March – October:</p><p>
Workdays: 8 - 16 h / Dog Walks 13 - 15.30 h</p>
<p>Saturday, Sunday: 8 - 17 h / Dog Walks 13 - 16.30 h</p></br><p>We are open 365 days a year!</p>",
		"postal_address" => "Postal address",
		"tel_one" => "Adoptions, info, reporting cases: +421 904 170 913 – We speak English",
		"tel_two" => "",
		"country"=>"Slovakia",
		"account_title"=> "Bank information",
		"account_one" => "Tatra banka: IBAN: SK5011000000002926886043, BIC: TATRSKBXXXX",
		"account_two" => "Poštová banka: IBAN: SK5865000000000020046882, BIC: POBNSKBA",
		"account_three" => "PayPal: send the payment to utulok@utulok-piestany.sk",
		"dogs_title" => "Dogs",
		"dog_male" => "Male",
		"dog_female" => "Female",
		"cats_title" => "Cats",
		"dogs_subtitle" => "All adult animals are castrated prior to adoption.",
		"cats_subtitle" => "All adult animals are castrated prior to adoption.",
		"filter_name" => "Filter by name",
		"filter_date" => "Filter by date of born",
		"select_month" => "Select month",
		"select_year" => "Select year",
		"filter" => "Filter",
		"no_filter" => "No filter",
		"adopted_on" => "Adopted on",
		"anonym" => "Do you wish to remain anonymous as a Patron on our website?",
		"back_to_all" => "Back to all",
		"search_in_reports" => "Search in reports",
		"type_a_word" => "Type a keyword...",
		"ph_name" => "",
		"ph_city" => "City",
		"ph_street" => "Street",
		"highest_bid" => "Highest bid",
		"from"=> "from",
		"posted" => "Posted",
		"end_auction" => "End of auction",
		"supporter_name" => "Supporters name",
		"one_pop_title" => "1-time",
		"one_pop_body" => "1-time-body",
		"one_pop_sub_title" => "1-time-sub",
		"tax" => "TAX",
		"tax_pop_title" => "2% INCOME TAX",
		"ico" => "IN.",
		"report_title_msg" => "Due to limited capacity, this page is only availabe in Slovak and German.<br>",
		"tax_title" => "Give your 2%",
		"tax_text" => "Dear Friends,<br>every year, from January to April, comes a decision time to whom you'll give the 2% of your income tax. We always hope that you'll favor the animals from Piestany shelter, because their dignified living depends mainly on this source of donations. They'll be waiting here, treated, safe and sate, for their second chance in loving homes solely thanks to your help.
		<br><br>The forms are downloadable from this page during the above mentioned period, or you can pick them up in person at places in Piestany that we'll publish at the right time.",
		"privacy_policy" => "Privacy policy",
		"privacy_policy_text" => "Welcome to our page. By continuing to browse our site you agree to our use of Cookie policy.<br><a href=\"privacy.php\">Read our Privacy Policy..</a>",
		"accept" => "Accept",
		"your_name"=> "",
		"your_full_name"=> "Full Name",
		"your_subject"=> "Subject",
		"your_message"=> "Message",
		"back_button"=> "Back",
		"adopt_info"=>"Please check your SPAM folder for our feedback.",
		"support_info"=>"IMPORTANT INFO: When making a money transfer, please type the name of the animal you’d like to support to the
Note field, so that we can match the payment with the particular dog or cat. Thank you.</br>
Please check your SPAM folder for our feedback.",
"repairs_title"=> "Repairs plan",
"repairs_path"=> "repairs_EN"

	),
	"de"=>array(
		"page_title" => "Tierheim Piešťany",
		"ABOUT_US" => "ÜBER UNS",
		"DOGS&CATS" => "TIERE",
		"REPORTS" => "MONATBERICHTE",
		"OTHER" => "ANDERE",
		"CONTACT" => "KONTAKT",
		"WELCOME_AT" => "WILKOMMEN BEI",
		"donate" => "schenk",
		"OUR_MISSION"=> "UNSERE AUFGABE",
		"OUR_TEAM" => "UNSERES TEAM",
		"IMPORTANT_INFO"=> "WICHTIGES INFO",
		"SPONSORS" => "SPONZOREN",
		"GALLERY" => "FOTOS",
		"DOGS" => "HUNDE",
		"CATS" => "KATZEN",
		"SEARCH" => "SUCHE",
		"ADOPT" => "ADOPTIEREN",
		"SUPPORT" => "PATENSCHAFT",
		"HELP" => "HELFEN SIE",
		"IN_HAPPY_HOME" => "VERMITTELT",
		"IN_MEMORIAM" => "WIR TRAUERN",
		"E-SHOP" => "E-SHOP",
		"AUCTION" => "AUKTION",
		"REPAIRS" => "ARBEITSPLAN",
		"SOS_CARD" => "SOS-Karte",
		"SOS_CARDdoc" => "SOS-Karte",
		"looking_for" => "Suche nach neue zu Hause...",
		"male" => "Manner",
		"female" => "Weiblich",
		"cat_male" => "Kater",
		"cat_female" => "Katze",
		"dog_male" => "Rüde",
		"dog_female" => "Hündin",
		"country"=>"Slowakei",
		"our_mission" => "Unsere Aufgabe",
		"how_adopt" => "Wie adoptieren?",
		"why_support" => "Warum unterstützen?",
		"about_adopt" => "Alles über Vermittlung",
		"about_support" => "Wie kann man helfen?",
		"visitors" => "Besuchern",
		"saved_dogs" => "Gerettete Hunde",
		"saved_cats" => "Gerettete Katze",
		"meet_team" => "Treffen Sie unseres Team",
		"our_sponsors" => "Unsere Sponzors",
		"our_place" => "Fotos aus dem Tierheim",
		"search_title" => "Suchen Sie für eine spezielle Tiere?",
		"select_type" => "Selektieren Sie einen Typ",
		"select_gender" => "Selektieren Sie Geschlecht",
		"castration" => "Kastration",
		"select_age" => "Selektieren Sie Alter",
		"search" => "Suchen",
		"adopt_title" => "Wie und warum adoptieren?",
		"adopt_subtitle1"=> "Ein Haustier zu adoptieren kann aufregend sein. Sie wählen für viele Jahre einen neuen Begleiter ...",
		"our_advice"=>"Unsere Rat...",
		"support_title" => "Seien Sie unserer Pate!",
        "support_subtitle" => "Sind Sie interessiert, ein Pate für ein Tier von unserem Tierheim zu werden?",
		"help_title" => "Warum und wie kann man helfen?",
		"help_subtitle" => "Unsere Hilfe für verlassene, obdachlose und misshandelte Tiere ist ganz abhängig und mőglich nur mit Hilfe
der Menschen mit gutem Herz",
		"dog" => "Hund",
		"cat" => "Katze",
		"male" => "Mannlich",
		"female" => "Weiblich",
		"cat_male" => "Kater",
		"cat_female" => "Katze",
		"yes" => "Ja",
		"no" => "Nein",
		"anonym" => "Wünschen Sie Ihr Name an unsere Web-Seite zu zeigen?",
		"adopted_title" => "Vermittelt",
		"inmemoriam_title" => "Wir trauern...",
		"inmemoriam_subtitle" => "Wir erinnern..",
		"reports_title" => "Monatsberichte",
		"annual_reports" => "Jahresberichte (SK)",
		"reports_archive" => "Archiv",
		"read_more" => "Lesen mehr...",
		"page" => "Page",
		"out_of" => "von",
		"products" => "Produkte",
		"product" => "Produkt",
		"eshop_subtitle" => "Über Eshop",
		"eshop_col1"=> "Kleider",
		"eshop_col2" => "Kragen, Leine",
		"eshop_col3"=> "Andere",
		"over" => "over",
		"auction" => "Auktion",
		"auction_subtitle" => "Auktion",
		"bid_price" => "Aktuelle Bid Preis",
		"first_price" => "Erste Preis",
		"end_date" => "Ablauf",
		"make_bid" => "Neue Bid",
		"contact_title"=> "Haben Sie Fragen? Kontaktieren Sie uns",
		"contact" => "Kontakt",
		"contact_sub" => "Bei Interesse können Sie uns jederzeit persönlich, telefonisch oder per E-Mail kontaktieren. Danke.",
		"an_home" => "Sitz des Tierheimes",
		"an_home_sub" => "Priemyselná 12a, Piešťany, Slowakei <br> GPS: +48° 35' 57.18\", +17° 48' 44.32\"",
		"more" => "Mehr...",
		"support" => "Patenschaft",
		"adopt_menu" => "Adoptieren",
		"name"=> "Name",
		"gender" => "Geschlecht",
		"breed" => "Rasse",
		"born" => "Geboren",
		"height" => "Schulterhöhe",
		"weight" => "Gewicht",
		"description" => "Beschreibung",
		"provide_value" => "Wert liefern",
		"dogs" => "Hunde",
		"cats"=> "Katze",
		"visit_us" => "Besuchen Sie uns",
		"quick_links" => "Quicklinks",
		"footer_find" => "Wo finden Sie uns?",
		"footer_open" => "Priemyselná 12a, Piešťany, Slowakei<br><br>November – Februar: 8 - 16 Uhr <br>- Spaziergänge mit Hunde 13 - 15.30 Uhr<br>
März – Oktober:<br>
Arbeitstage: 8 - 16 Uhr <br>- Spaziergänge mit Hunde 13 - 15.30 Uhr<br>
Samstag, Sonntag: 8 - 17 Uhr <br>- Spaziergänge mit Hunde 13 - 16.30 Uhr<br><br>Wir sind 365  Tage im Jahr geöffnet!",
		"footer_row1" => "Priemyselná 12a, Piešťany, Slowakei",
		"footer_row2" => "Büro: +421 904 170 913 - Wir sprechen Deutsch",
		"footer_row4" => "utulok@utulok-piestany.sk",
		"footer_row3" => "IBAN: SK5011000000002926886043<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;BIC: TATRSKBXXXX",
		"close" => "Schließen",
		"support_modal_title" => "Unterstützung",
		"your_full_name" => "Ihre Name",
		"ZIP" => "ZIP",
		"city" => "Stadt",
		"street" => "Straße",
		"support_btn" => "Mimmt Patenschaft",
		"support_msg" => "Vielen Dank, Ihre Unterstützunganfrage wurde erfolgreich gesendet! Wir werden uns bald bei Ihnen melden.",
		"adopt_modal_title"=> "Adoptier",
		"kind_of_keeping" => "Art zu halten",
		"inside" => "Trinnen",
		"outside" => "Draußen",
		"in_out" => "Trinnen & Draußen",
		"other_pets" => "Andere Tiere im Haushalt",
		"other_pets2" => "Andere Tiere im Haushalt",
		"address" => "Addresse",
		"optional" => "Optional",
		"adopt_btn" => "Adopt",
		"adopt_msg" => "Vielen Dank, Ihre Unterstützungtanfrage wurde erfolgreich gesendet! Wir werden uns bald bei Ihnen melden.",
		"nick_name" => "Nick Name (auf der Seite angezeigt)",
		"not_public" => "nicht public",
		"your_bid" => "Ihre Bid",
		"comment" => "Komment",
		"not_required" => "nicht benötigt",
		"bid_btn" => "Bid machen",
		"bid_msg" => "Erfolgreich gesendet!",
		"buy" => "Kaufen",
		"buy_btn"=> "Kaufen",
		"description" => "Beschreibung",
		"price"=> "Price",
		"quantity" => "Menge",
		"condition" => "Kondition",
		"type" => "Typ",
		"contact_open" => "<p>November – Februar: 8 - 16 Uhr / Spaziergänge mit Hunde 13 - 15.30 Uhr
</p><p>März – Oktober:</p><p>
Arbeitstage: 8 - 16 Uhr / Spaziergänge mit Hunde  13 - 15.30 Uhr</p>
<p>Samstag, Sonntag: 8 - 17 Uhr / Spaziergänge mit Hunde  13 - 16.30 Uhr</p></br><p>Wir sind 365 Tage im Jahr geöffnet!</p>",
		"postal_address" => "Postanschrift",
		"tel_one" => "Büro: +421 904 170 913 - Wir sprechen Deutsch",
		"tel_two" => "",
		"account_title"=> "Konto-Nr",
		"account_one" => "Konto Nr. IBAN: SK5865000000000020046882,  BIC: POBN SKBA",
		"account_two" => "Konto Nr. IBAN: SK501100000000292688604,  BIC: TATRSKBXXXX",
		"account_three" => "PayPal: Senden Sie den Betrag an utulok@utulok-piestany.sk",
		"dogs_title" => "Hunde",
		"cats_title" => "Katze",
		"dogs_subtitle" => "Erwachsene Hündinen sind zu Vermittlung nur kastriert.",
		"cats_subtitle" => "Erwachsene Katze und Kater sind zu Vermittlung nur kastriert.",
		"filter_name" => "Filter nach Name",
		"filter_date" => "Filter nach Geboren",
		"select_month" => "Monat auswählen",
		"select_year" => "Jahre auswählen",
		"filter" => "Filter",
		"no_filter" => "No filter",
		"adopted_on" => "Adopted on",
		"back_to_all" => "Back to all",
		"search_in_reports" => "Suche in Reports",
		"type_a_word" => "Type a keyword...",
		"ph_name" => "",
		"ph_city" => "City",
		"ph_street" => "Street",
		"highest_bid" => "Highest bid",
		"from"=> "from",
		"posted" => "Posted",
		"end_auction" => "End of auction",
		"supporter_name" => "Name des Unterstützers",
		"one_pop_title" => "1-time",
		"one_pop_body" => "1-time-body",
		"one_pop_sub_title" => "1-time-sub",
		"tax" => "TAX",
		"tax_pop_title" => "2% AUS DER STEUER",
		"ico" => "Id-Nr. der Organisation",
		"report_title_msg" => "Aufgrund der begrenzten Kapazität ist diese Seite nur in slowakischer und deutscher Sprache verfügbar.<br>",
		"tax_title" => "Give your 2%",
		"tax_text" => "Liebe Freunde,
		<br>
Jedes Jahr kőnnt ihr euch entscheiden,wem schenkt ihr 2% aus der Steuer und wir hoffen,das werden wieder die
Tiere aus unserem Tierheim sein.
<br>
Nur mit eurer Hilfe werden alle satt und können in Sicherheit sein. Sie können ohne Sorgen auf eine zweite Chance
hoffen und auf ihre neue Familien bei uns warten.
<br>
Das Formular ist verfügbar hier.<br>",
		"tax_text2" => "The forms are downloadable from this page during the above mentioned period, or you can pick them up in person at places in Piestany that we'll publish at the right time.",
		"privacy_policy" => "Datenschutzerklärung",
		"privacy_policy_text" => "Willkommen auf unserer Seite. Wenn Sie weiterhin auf unserer Website surfen, stimmen Sie unserer Verwendung der Cookie-Richtlinie zu.<br><a href=\"privacy_de.php\"> Lesen Sie unsere Datenschutzerklärung..</a>",
		"accept" => "Accept",
		"your_name"=> "",
		"your_full_name"=> "Full Name",
		"your_subject"=> "Subject",
		"your_message"=> "Message",
		"back_button"=> "Zurück",
		"support_info"=>"EINE WICHTIGE INFORMATION : Bei Zahlungen auf unser Konto bitten wir Sie, das Tier zu identifizieren, für welches
das Geld überwiesen wird. Den Namen des Tieres tragen Sie, bitte, in das Feld Verwendungszweck ein. Vielen Dank!</br>
Bitte überprüfen Sie Ihren SPAM-Ordner auf unser Feedback.",
		"adopt_info"=>"Bitte überprüfen Sie Ihren SPAM-Ordner auf unser Feedback.",
		"repairs_title"=> "Arbeitsplan",
"repairs_path"=> "repairs_DE"
	),
	"sk"=>array(
		"page_title" => "Útulok Piešťany",
		"ABOUT_US" => "O NÁS",
		"DOGS&CATS" => "PSÍKOVIA & MAČIČKY",
		"REPORTS" => "SPRÁVY Z ÚTULKU",
		"OTHER" => "INÉ",
		"CONTACT" => "KONTAKT",
		"WELCOME_AT" => "VITAJTE!",
		"donate" => "daruj",
		"OUR_MISSION"=> "NAŠA MISIA",
		"OUR_TEAM" => "NÁŠ TEAM",
		"IMPORTANT_INFO"=> "DÔLEŽITÉ INFO",
		"SPONSORS" => "SPONZORI",
		"GALLERY" => "NÁŠ ÚTULOK",
		"DOGS" => "PSÍČKOVIA NA ADOPCIU",
		"CATS" => "MAČIČKY NA ADOPCIU",
		"SEARCH" => "HĽADANIE",
		"ADOPT" => "ADOPTUJ",
		"SUPPORT" => "PATRONÁT",
		"HELP" => "AKO NÁM POMÔCŤ?",
		"IN_HAPPY_HOME" => "NAŠLI DOMOV",
		"IN_MEMORIAM" => "OPUSTILI NÁS",
		"E-SHOP" => "E-SHOP",
		"AUCTION" => "AUKCIA",
		"REPAIRS" => "PLÁN PRÁC",
		"SOS_CARD" => "SOS kartička",
		"SOS_CARDdoc" => "SOS_karticka",
		"looking_for" => "Hľadajú nový domov...",
		"male" => "psík",
		"female" => "fenka",
		"dog_male" => "psík",
		"dog_female" => "fenka",
		"cat_male" => "kocúr",
		"cat_female" => "mačka",
		"our_mission" => "Naša misia",
		"how_adopt" => "Ako si adoptovať zvieratko z útulku?",
		"why_support" => "Prečo nás podporiť?",
		"about_adopt" => "Všetko o adopcii...",
		"about_support" => "Ako môžete promôcť?",
		"visitors" => "Návštevníkov",
		"saved_dogs" => "Zachránených psíkov",
		"saved_cats" => "Zachránených mačičiek",
		"meet_team" => "Spoznajte <br> náš team",
		"our_sponsors" => "Naši sponzori",
		"our_place" => "Náš útulok",
		"search_title" => "Hľadáte konkrétne zvieratko?",
		"select_type" => "Vyberte druh",
		"select_gender" => "Vyberte pohlavie",
		"castration" => "Kastrácia",
		"select_age" => "Vyberte vek",
		"anonym" => "Želáte si, aby bolo uvedené Vaše meno na našej webovej stránke?",
		"search" => "Hľadať",
		"adopt_title" => "Prečo adoptovať?",
		"adopt_subtitle1"=> "Adoptovať zvieratko je veľká radosť. Vyberáte si spoločníka na mnoho rokov...",
		"our_advice"=>"Pár našich rád...",
		"support_title" => "Vyber si hrdo svojho chránenca!",
		"support_subtitle" => "Jedinečná &quot;malá veľká&quot; pomoc pre zvieratká v našom útulku.",
		"help_title" => "Prečo a ako nám pomôcť?",
		"help_subtitle" => "Naša pomoc opusteným zvieratkám je celkom závislá a možná len vďaka pomoci ľudi ako vy - ľudí s dobrým srdcom...",
		"dog" => "Psík",
		"cat" => "Mačička",
		"male" => "Psík",
		"female" => "Fenka",
		"yes" => "Áno",
		"no" => "Nie",
		"adopted_title" => "Zvieratká, ktoré majú nový domov",
		"inmemoriam_title" => "Opustili nás...",
		"inmemoriam_subtitle" => "Na nebesiach je miesto, ktorému sa hovorí Dúhový most. Keď zomrie zviera, odchádza za tento Dúhový most. Pre našich milých kamarátov sú tam lúky a kopce, kde môžu behať a spoločne sa hrať. Je tam veľa jedla, vody, slnečného svitu a naši priatelia sú v teple a pohodlí. Všetky choré a staré zvieratá sú opäť zdravé a plné síl - tak ako so ich pamätáme z našich snov a minulosti.",
		"reports_title" => "Správy z útulku",
		"annual_reports" => "Výročné správy",
		"reports_archive" => "Archív správ",
		"read_more" => "Čítaj viac...",
		"page" => "Stránka",
		"country"=>"",
		"out_of" => "z",
		"products" => "Produkty",
		"product" => "Produkt",
		"eshop_subtitle" => "Peniaze získané z predaja budú použité pre potreby našich chránencov - psíkov a mačičiek.",
		"eshop_col1"=> "Oblečky",
		"eshop_col2" => "Obojky, vodítka, popruhy",
		"eshop_col3"=> "Iné zaujímavé veci",
		"over" => "nad",
		"auction" => "Aukcia",
		"auction_subtitle" => "Vítame Vás v sekcii Aukcia, v ktorej prebieha dražba predmetov v prospech Útulku Piešťany.",
		"bid_price" => "Ponúknutá suma",
		"first_price" => "Vyvolávacia cena",
		"end_date" => "Koniec aukcie",
		"make_bid" => "Zvýš ponuku",
		"contact_title"=> "Máte otázky? Kontaktujte nás",
		"contact" => "Kontakt",
		"contact_sub" => "V prípade záujmu nás neváhajte kedykoľvek kontaktovať osobne, telefonicky alebo emailom. Ďakujeme.",
		"an_home" => "Útulok Piešťany",
		"an_home_sub" => "Priemyselná 12a, Piešťany <br> GPS súradnice: +48° 35' 57.18\", +17° 48' 44.32\"",
		"more" => "Viac info",
		"support" => "Staň sa Patrónom",
		"adopt_menu" => "Adoptuj",
		"name"=> "Meno",
		"gender" => "Pohlavie",
		"breed" => "Rasa",
		"born" => "Dátum narodenia",
		"height" => "Výška",
		"weight" => "Váha",
		"description" => "Viac info",
		"provide_value" => "Pridaj hodnotu",
		"dogs" => "Psíkovia",
		"cats"=> "Mačičky",
		"visit_us" => "Navštívte nás",
		"quick_links" => "Rýchle odkazy",
		"footer_find" => "Kontakty",
		"footer_open" => "Priemyselná 12a, Piešťany<br><br>November – Február: 8 - 16 h <br>- Venčenie 13 - 15.30 h<br>
Marec – Október:<br>
Pracovné dni: 8 - 16 h <br>- Venčenie 13 - 15.30 h<br>
Sobota, nedeľa: 8 - 17 h <br>- Venčenie 13 - 16.30 h<br><br>Otvorené máme 365 dní v roku!",
		"footer_row2" => "+421 904 170 913",
		"footer_row1" => "Priemyselná 12a, Piešťany",
		"footer_row4" => "utulok@utulok-piestany.sk",
		"footer_row3" => "IBAN: SK5011000000002926886043<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;BIC: TATRSKBXXXX",
		"close" => "Zatvoriť",
		"support_modal_title" => "Staňte sa Patrónom",
		"your_full_name" => "Meno a priezvisko",
		"ZIP" => "PSČ",
		"city" => "Mesto",
		"street" => "Ulica",
		"support_btn" => "Chcem byť Patrónom",
		"support_msg" => "Ďakujeme, vaša žiadosť o Patronát bola úspešne odoslaná! Budeme vás čoskoro kontaktovať.",
		"adopt_modal_title"=> "Adoptujte",
		"kind_of_keeping" => "Podmienky",
		"inside" => "Vnútri",
		"outside" => "Vonku",
		"in_out" => "Vnútri & Vonku",
		"other_pets" => "Iné zvieratá v domácnosti",
		"other_pets2" => "Druh zvierat v domácnosti",
		"address" => "Adresa",
		"optional" => "nepovinné",
		"adopt_btn" => "Chcem adoptovať",
		"adopt_msg" => "Ďakujeme, vaša žiadosť o Adopciu bola úspešne odoslaná! Budeme vás čoskoro kontaktovať.",
		"nick_name" => "Prezývka (zverejnená na stránke)",
		"not_public" => "nezverejnené",
		"your_bid" => "Vaša ponuka",
		"comment" => "Poznámka",
		"not_required" => "nepovinný údaj",
		"bid_btn" => "Prihodiť",
		"bid_msg" => "Úspešne odoslané!",
		"buy" => "Kúpiť",
		"buy_btn"=> "Chcem kúpiť",
		"description" => "Popis",
		"price" => "Cena",
		"quantity"=> "Množstvo",
		"condition"=> "Stav",
		"type" => "Typ",
		"contact_open" => "<p>November – Február: 8 - 16 h / Venčenie 13 - 15.30 h
</p><p>Marec – Október:</p><p>
Pracovné dni: 8 - 16 h / Venčenie 13 - 15.30 h </p><p>
Sobota, nedeľa: 8 - 17 h / Venčenie 13 - 16.30 h</p>
</br><p>Otvorené máme 365 dní v roku!</p>",
		"postal_address" => "Písomný kontakt",
		"tel_one" => "Adopcie, nahlasovanie prípadov: 0904 170 913",
		"tel_two" => "Info: 0903 207 306, 0911 333 349, 0911 179 113",
		"account_title"=> "Číslo účtu",
		"account_one" => "Tatra banka: IBAN: SK5011000000002926886043, BIC: TATRSKBXXXX",
		"account_two" => "Poštová banka: IBAN: SK5865000000000020046882, BIC: POBNSKBA",
		"account_three" => "PayPal: platbu poslať na utulok@utulok-piestany.sk",
		"dogs_title" => "Psíkovia na adopciu",
		"cats_title" => "Mačičky na adopciu",
		"dogs_subtitle" => "Dospelé zvieratká vydávame na adopciu len kastrované.",
		"cats_subtitle" => "Dospelé zvieratká vydávame na adopciu len kastrované.",
		"filter_name" => "Filtrovať podľa mena",
		"filter_date" => "Filtrovať podľa dátumu narodenia",
		"select_month" => "Vyber mesiac",
		"select_year" => "Vyber rok",
		"filter" => "Filtrovať",
		"no_filter" => "Zrušiť filter",
		"adopted_on" => "Adoptovaný dňa",
		"back_to_all" => "Späť ku Správam",
		"search_in_reports" => "Hľadať v správach",
		"type_a_word" => "Kľúčové slová...",
		"ph_name" => "Vaše celé meno",
		"ph_city" => "Č.popisné, PSČ + Mesto",
		"ph_street" => "Nepovinný údaj",
		"highest_bid" => "Najvyššia ponúknutá suma",
		"from"=> "od.",
		"posted" => "Zverejnené",
		"end_auction" => "Koniec aukcie",
		"supporter_name" => "Patrónom tohto zvieratka je",
		"one_pop_title" => "1-time",
		"one_pop_body" => "1-time-body",
		"one_pop_sub_title" => "1-time-sub",
		"tax" => "z dane",
		"tax_pop_title" => "2% Z DANE",
		"ico" => "IČO",
		"report_title_msg" => "",
		"tax_title" => "Daruj svoje 2%",
		"tax_text" => "Milí priatelia,
		<br>
opäť prichádza čas rozhodovania, komu venovať 2% z vašich daní a opäť dúfame, že aj tento rok získajú vašu
priazeň zvieratká z piešťanského útulku. Ich dôstojné žitie a bytie závisí najmä od prispievateľov, len s vašou
pomocou budú čakať nasýtení, ošetrení a v bezpečí na svoju druhú šancu v rodinách.
<br><br>
Za peniaze šťastie nekúpiš, ale zachrániš útulkáča. Daruj 2%.
<br><br>
Vyplnené tlačivá na poukázanie 2% daní si môžete stiahnuť tu. Užitočné informácie k poukázaniu 2% daní nájdete
na stránke www.rozhodni.sk
<br><br>
Ďakujeme!
<br>
Váš Útulok Piešťany",
		"tax_text2" => "Vyplnené tlačivá na poukázanie 2% z daní si v horeuvedenom období môžete stiahnuť práve tu alebo osobne sú tiež k dispozícii na konkrétnych miestach v Piešťanoch, ktoré v správnom čase zverejníme.",
		"privacy_policy" => "Ochrana osobných údajov",
		"privacy_policy_text" => "Vitajte na našej stránke. Pokračovaním v jej prehliadaní súhlasíte s používaním cookies. Pre viac informácií si môžete prečítať celé znenie o <a href=\"privacy_sk.php\">ochrane osobných údajov.</a>",
		"accept" => "Súhlasím",
		"your_name"=> "Vaše meno",
		"your_full_name"=> "Meno a Priezvisko",
		"your_subject"=> "Predmet správy",
		"your_message"=> "Vaša správa",
		"back_button"=> "Späť",
		"support_info"=>"DÔLEŽITÁ INFORMÁCIA: Pri zasielaní platieb na náš účet Vás prosíme o identifikáciu zvieratka, pre ktoré je platba
zasielaná. Meno zvieratka, prosím, uveďte do kolonky Správa pre prijímateľa.</br>
Prosím, skontrolujte Váš SPAM priečinok, je možné, že naša odozva bude doručená tam.",
		"adopt_info"=>"Prosím, skontrolujte Váš SPAM priečinok, je možné, že naša odozva bude doručená tam.",
		"repairs_title"=> "Plán prác",
"repairs_path"=> "repairs_SK"
	)
)?>